tpc_userpoints_ext.transaction_operation_config.*:
  type: config_entity
  label: 'Transaction Operation Config'
  mapping:
    id:
      type: string
      label: 'ID'
    defaultPointValue:
      type: integer
      label: 'Default Point Value'
      